### ISSUE TITLE
Editting the contrbuting.md

### ISSUE THREAD

**Issue by sahitpj** [pydatagn/Community#1]

**Comment by kumiDa** [comment]
Can I work on this?

**Comment by sahitpj** [comment]
Yeah go for it @rahul-kumi . let me know if you have any doubts 😄

**Comment by kumiDa** [comment]
@sahitpj in PR #2, I have included a basic Contribution instruction.
Let me know if there is something more to be added.

**Comment by sahitpj** [comment]
hey @rahul-kumi can you check out the review
